config/routes.rb
Myvoice::Application.routes.draw do
  resources :chunks

  resources :users

end

app/models/chunk.rb
class Chunk < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
  # GET /chunks
  # GET /chunks.json

  before_filter :setupsimperium

  def setupsimperium
    require 'simperium'
    @auth = Simperium::Auth.new('proficiency-stitches-d7f', '1c3b994783a6430e9f6f595a1be93c38')
    @token = @auth.authorize('email1@address.com', 'password')
    @api = Simperium::Api.new('proficiency-stitches-d7f', @token)
  end    

  def index
    @chunks = Chunk.all

    @schunks = @api.chunk.index(:data=>true, :mark=>nil, :limit=>nil, :since=>nil)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chunks }
    end
  end

  # GET /chunks/1
  # GET /chunks/1.json
  def show
    @chunk = Chunk.find(params[:id])

    @schunk = @api.chunk.get(@chunk.label)

    @schunk.each_pair do |key, value|
        @key = key
        @value = value
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chunk }
    end
  end

  # GET /chunks/new
  # GET /chunks/new.json
  def new
    @chunk = Chunk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chunk }
    end
  end

  # GET /chunks/1/edit
  def edit
    @chunk = Chunk.find(params[:id])

    @schunk = @api.chunk.get(@chunk.label)

    @schunk.each_pair do |key, value|
        @key = key
        @value = value
    end

  end

  # POST /chunks
  # POST /chunks.json
  def create
    @chunk = Chunk.new(params[:chunk])

    @data = {@chunk.key => @chunk.value}

    @label = @api.chunk.new(@data)

    @chunk.label = @label

    respond_to do |format|
      if @chunk.save
        format.html { redirect_to @chunk, notice: 'Chunk was successfully created.' }
        format.json { render json: @chunk, status: :created, location: @chunk }
      else
        format.html { render action: "new" }
        format.json { render json: @chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chunks/1
  # PUT /chunks/1.json
  def update
    @chunk = Chunk.find(params[:id])
    
    respond_to do |format|
      if @chunk.update_attributes(params[:chunk])

        #Rails chunk object updated, use this to update simperium. 
        @data = {@chunk.key => @chunk.value}
        @api.chunk.set(@chunk.label, @data)

        format.html { redirect_to @chunk, notice: (@newdata) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chunk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chunks/1
  # DELETE /chunks/1.json
  def destroy
    @chunk = Chunk.find(params[:id])

    @api.chunk.delete(@chunk.label)

    @chunk.destroy

    respond_to do |format|
      format.html { redirect_to chunks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    require 'simperium'
    auth = Simperium::Auth.new('proficiency-stitches-d7f', '1c3b994783a6430e9f6f595a1be93c38')
    #@token = auth.create('email1@address.com', 'password')
    @token = auth.authorize('email1@address.com', 'password')

    #Talking to Simperium
    api = Simperium::Api.new('proficiency-stitches-d7f', @token)
    #@chunk = api.chunk

    @chunkid = api.chunk.new({'title3' => '3'})

    #@showchunk = api.chunk.get('bcf13f5109b00130c980704da27e5162')

    #api.chunk.delete('2fec7ff00a6001309a77704da27e5162')
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chunks_helper.rb
module ChunksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chunks/_form.html.erb
<%= form_for(@chunk) do |f| %>
  <% if @chunk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chunk.errors.count, "error") %> prohibited this chunk from being saved:</h2>

      <ul>
      <% @chunk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key, :value => @key %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value, :value => @value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chunks/edit.html.erb
<h1>Editing chunk</h1>

<%= render 'form' %>

<%= link_to 'Show', @chunk %> |
<%= link_to 'Back', chunks_path %>

app/views/chunks/index.html.erb
<h1>Listing chunks</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Key</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chunks.each do |chunk| %>
  <tr>
    <td><%= chunk.label %></td>
    <td><%= chunk.key %></td>
    <td><%= chunk.value %></td>
    <td><%= link_to 'Show', chunk %></td>
    <td><%= link_to 'Edit', edit_chunk_path(chunk) %></td>
    <td><%= link_to 'Destroy', chunk, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chunk', new_chunk_path %>

<br>
<br>
Schunks = <%=raw @schunks %>

app/views/chunks/new.html.erb
<h1>New chunk</h1>

<%= render 'form' %>

<%= link_to 'Back', chunks_path %>

app/views/chunks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @chunk.label %>
</p>
<p>
  <b>Key:</b>
  <%= @key %>
</p>
<p>
  <b>Value:</b>
  <%= @value %>
</p>


<%= link_to 'Edit', edit_chunk_path(@chunk) %> |
<%= link_to 'Back', chunks_path %>
<br>
<br>
SubmitData = <%= @submitdata %>
<br>
<br>
SChunk = <%= @schunk %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myvoice</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<a href="./users">Users</a>
<a href="./chunks">Chunks</a>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

<br>
Token = <%= @token %><br>

<br>
@Chunk = <%= @chunk %><br>

<br>
@Chunkid = <%= @chunkid %><br>

<br>
@ChunkShow = <%= @showchunk %><br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>